#!/bin/sh
aws ecr get-login-password --region region | docker login --username AWS --password-stdin $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
export AWS_REGISTRY_URL="$AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$BITBUCKET_REPO_SLUG"
export BUILD_ID="$BITBUCKET_BRANCH-$BITBUCKET_COMMIT-$BITBUCKET_BUILD_NUMBER"
docker build -t ${AWS_REGISTRY_URL}:$BUILD_ID .
docker push ${AWS_REGISTRY_URL}:$BUILD_ID
docker tag ${AWS_REGISTRY_URL}:$BUILD_ID ${AWS_REGISTRY_URL}:development
docker push ${AWS_REGISTRY_URL}:development
echo $BUILD_ID > buildid.txt
